#!/usr/bin/env php
<?php

declare(strict_types=1);

$devCliSrcPath = __DIR__ . '/devCliSrc';
$composerLockHashCachePath = $devCliSrcPath . '/composerLockHashCache';
$composerLockFilePath = $devCliSrcPath . '/composer.lock';
$vendorAutoLoad = $devCliSrcPath . '/vendor/autoload.php';

if (!file_exists($composerLockHashCachePath)) {
    touch($composerLockHashCachePath);
}

$composerLockHash = md5_file($composerLockFilePath);
$composerLockHashCache = trim(
    file_get_contents($composerLockHashCachePath)
);

if (
    !file_exists($vendorAutoLoad) ||
    $composerLockHash !== $composerLockHashCache
) {
    echo 'The CLI dependencies have not been installed, installing now…';
    echo PHP_EOL;
    echo PHP_EOL;
    shell_exec('cd ' . $devCliSrcPath . ' && composer install');
    file_put_contents(
        $composerLockHashCachePath,
        $composerLockHash
    );
    echo PHP_EOL;
    echo PHP_EOL;
    echo 'CLI dependencies have now been installed…';
    echo PHP_EOL;
    echo PHP_EOL;
}

require __DIR__ . '/devCliSrc/cli.php';
