services:
  api:
    env_file:
      - ./api/.env.dev
      - ./api/.env.local
    container_name: smrc_api
    image: ghcr.io/st-mark-reformed/smrc-2025-api
    environment:
      - HOSTNAME=smrc_api
      - ENABLE_XDEBUG=1
      - ENABLE_PHP_DEV_CONFIG=1
#    healthcheck:
#      disable: true
#      test: '0'
    volumes:
      - ./api/.bash_history:/root/.bash_history:delegated
      - ../api:/var/www:delegated
    expose:
      - 80
    networks:
      traefik:
      default:
        aliases:
            - api.stmarkreformed.localtest.me
    labels:
      ## Traefik config ##
      - traefik.enable=true
      - traefik.docker.network=traefik

      ## Traefik Web ##
      # Web redirect to https
      - traefik.http.routers.stmarkreformed_api.entrypoints=web
      - traefik.http.routers.stmarkreformed_api.rule=Host(`api.stmarkreformed.localtest.me`)
      - traefik.http.routers.stmarkreformed_api.middlewares=https-redirect

      # Web secure
      - traefik.http.routers.stmarkreformed_api-secure.entrypoints=websecure
      - traefik.http.routers.stmarkreformed_api-secure.tls=true
      - traefik.http.routers.stmarkreformed_api-secure.rule=Host(`api.stmarkreformed.localtest.me`)
    ports:
      - "49195:80"

networks:
  traefik:
    name: traefik
    external: true
